[package]
name = "readrust"
version = "0.1.0"
authors = ["Florian Gilcher <florian.gilcher@asquera.de>"]

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
clap = "2.29"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
prettytable-rs = "0.6"
